"""Generate no-op shared libraries for OpenHarmony platform libs.

dockerharmony ships no OpenHarmony platform libraries, so libQt6Core cannot be
loaded and no build-time tool that links it can run. Most of what Qt6Core needs
is satisfied by copying the real libraries in, but libace_napi drags in the
ArkTS engine and libohfileuri the system ability manager and IPC, neither of
which belongs in a build container. Those get stubs instead.

Symbols are read from the SDK's own link-time stubs, so the set cannot drift
from the SDK the image is built against.
"""

import os, pathlib, subprocess, sys

# Never stub these: the loader and the C++ runtime are real and present.
NEVER_SHIM = {"libc.so", "libc++.so", "libc++_shared.so", "libc++abi.so"}

# Where a real implementation may already exist. Mirrors the interesting part
# of OHOS musl's namespace config plus the Harmonybrew prefix.
REAL_LIB_DIRS = [
    "/system/lib64", "/system/lib64/ndk", "/system/lib64/platformsdk",
    "/system/lib64/chipset-sdk", "/system/lib64/chipset-pub-sdk",
    "/system/lib64/chipset-sdk-sp", "/lib64", "/lib64/platformsdk",
    "/lib64/chipset-pub-sdk", "/lib64/chipset-sdk", "/lib64/chipset-sdk-sp",
    "/lib", "/usr/lib", "/usr/local/lib",
]

TEMPLATE = '''/* Generated by gen-shims.py from the SDK stub of %(lib)s. Do not edit.
 *
 * Returns a non-zero error rather than a success code on purpose: a build-time
 * tool has no business calling into these, and a fake success would hand the
 * caller uninitialised out-parameters. Set OHOS_SHIM_TRACE to find out whether
 * anything actually calls them.
 */
#include <stdio.h>
#include <stdlib.h>

static void shim_trace(const char *name)
{
    static int on = -1;
    if (on < 0)
        on = getenv("OHOS_SHIM_TRACE") != NULL;
    if (on)
        fprintf(stderr, "ohos-shim: %(lib)s: %%s called\\n", name);
}

'''


def symbols(nm, stub):
    out = subprocess.run([nm, "--dynamic", "--defined-only", "--extern-only", stub],
                         check=True, capture_output=True, text=True).stdout
    for line in out.splitlines():
        parts = line.split()
        if len(parts) < 2:
            continue
        kind, name = parts[-2], parts[-1]
        if name not in ("_init", "_fini"):
            yield kind, name


def main():
    sdk = pathlib.Path(sys.argv[1])
    outdir = pathlib.Path(sys.argv[2])
    cc = sys.argv[3]
    nm = str(sdk / "llvm/bin/llvm-nm")
    stubs = sdk / "sysroot/usr/lib/aarch64-linux-ohos"
    work = pathlib.Path("/tmp/ohos-shims")
    work.mkdir(parents=True, exist_ok=True)

    extra_dirs = [pathlib.Path(d) for d in REAL_LIB_DIRS]
    brew = os.environ.get("HOMEBREW_PREFIX")
    if brew:
        extra_dirs.append(pathlib.Path(brew) / "lib")

    generated = skipped = 0
    for stub in sorted(stubs.glob("*.so")):
        lib = stub.name
        if lib in NEVER_SHIM:
            skipped += 1
            continue
        # A real implementation beats a stub; never shadow one.
        if any((d / lib).exists() for d in extra_dirs):
            skipped += 1
            continue
        body = [TEMPLATE % {"lib": lib}]
        count = 0
        for kind, name in symbols(nm, str(stub)):
            if kind.upper() == "T":
                body.append('long %s(void) { shim_trace("%s"); return 9; }\n' % (name, name))
            else:
                body.append("long %s = 0;\n" % name)
            count += 1
        if not count:
            skipped += 1
            continue
        src = work / (lib + ".c")
        src.write_text("".join(body))
        subprocess.run([cc, "-shared", "-fPIC", "-O0", "-o", str(outdir / lib),
                        str(src), "-Wl,-soname," + lib], check=True)
        generated += 1
    print("shims: generated %d, skipped %d (real implementation present)"
          % (generated, skipped))


if __name__ == "__main__":
    main()
