"""Generate no-op shared libraries for OpenHarmony platform libs.

dockerharmony ships no OpenHarmony platform libraries, so libQt6Core cannot be
loaded and no build-time tool that links it can run. Most of what Qt6Core needs
is satisfied by copying the real libraries in, but libace_napi drags in the
ArkTS engine and libohfileuri the system ability manager and IPC, neither of
which belongs in a build container. Those get stubs instead.

Symbols are read from the SDK's own link-time stubs, so the set cannot drift
from the SDK the image is built against.
"""

import pathlib, subprocess, sys

SHIM_LIBS = ["libace_napi.z.so", "libohfileuri.so", "libohenvironment.so"]

TEMPLATE = '''/* Generated by gen-shims.py from the SDK stub of %(lib)s. Do not edit.
 *
 * Returns a non-zero error rather than a success code on purpose: a build-time
 * tool has no business calling into these, and a fake success would hand the
 * caller uninitialised out-parameters. Set OHOS_SHIM_TRACE to find out whether
 * anything actually calls them.
 */
#include <stdio.h>
#include <stdlib.h>

static void shim_trace(const char *name)
{
    static int on = -1;
    if (on < 0)
        on = getenv("OHOS_SHIM_TRACE") != NULL;
    if (on)
        fprintf(stderr, "ohos-shim: %(lib)s: %%s called\\n", name);
}

'''


def symbols(nm, stub):
    out = subprocess.run([nm, "--dynamic", "--defined-only", "--extern-only", stub],
                         check=True, capture_output=True, text=True).stdout
    for line in out.splitlines():
        parts = line.split()
        if len(parts) < 2:
            continue
        kind, name = parts[-2], parts[-1]
        if name not in ("_init", "_fini"):
            yield kind, name


def main():
    sdk = pathlib.Path(sys.argv[1])
    outdir = pathlib.Path(sys.argv[2])
    cc = sys.argv[3]
    nm = str(sdk / "llvm/bin/llvm-nm")
    stubs = sdk / "sysroot/usr/lib/aarch64-linux-ohos"
    work = pathlib.Path("/tmp/ohos-shims")
    work.mkdir(parents=True, exist_ok=True)

    for lib in SHIM_LIBS:
        stub = stubs / lib
        if not stub.exists():
            sys.exit("SDK stub not found: %s" % stub)
        body = [TEMPLATE % {"lib": lib}]
        count = 0
        for kind, name in symbols(nm, str(stub)):
            if kind.upper() == "T":
                body.append('long %s(void) { shim_trace("%s"); return 9; }\n' % (name, name))
            else:
                body.append("long %s = 0;\n" % name)
            count += 1
        src = work / (lib + ".c")
        src.write_text("".join(body))
        subprocess.run([cc, "-shared", "-fPIC", "-O1", "-o", str(outdir / lib),
                        str(src), "-Wl,-soname," + lib], check=True)
        print("generated %s with %d stubs" % (lib, count))


if __name__ == "__main__":
    main()
